import type { GitHubUser, GitHubRepo, PortalItem } from '../../types/portal';

// ─────────────────────────────────────────────────────────────────────────────
//  Mock data — used in demo mode (no real API calls)
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_USER: GitHubUser = {
  login: 'demo-user',
  name: 'Demo User',
  bio: 'Este es un portal de demostración. Configura tu usuario en src/config/portal.ts',
  avatar_url: 'https://avatars.githubusercontent.com/u/583231?v=4',
  html_url: 'https://github.com/octocat',
  public_repos: 12,
  followers: 42,
};

const makeRepo = (
  name: string,
  description: string,
  topics: string[],
  language: string,
  hasPages: boolean = false,
  stars: number = 0
): GitHubRepo => ({
  id: Math.floor(Math.random() * 100000),
  name,
  full_name: `demo-user/${name}`,
  description,
  html_url: `https://github.com/demo-user/${name}`,
  homepage: hasPages ? `https://demo-user.github.io/${name}` : null,
  topics,
  stargazers_count: stars,
  language,
  updated_at: new Date(Date.now() - Math.random() * 30 * 24 * 3600 * 1000).toISOString(),
  created_at: new Date(Date.now() - Math.random() * 365 * 24 * 3600 * 1000).toISOString(),
  has_pages: hasPages,
  default_branch: 'main',
  fork: false,
  archived: false,
});

export const MOCK_ITEMS: PortalItem[] = [
  {
    id: 'mi-app-increible',
    kind: 'page',
    title: 'Mi App Increíble',
    description: 'Una aplicación web completa con autenticación, base de datos y más. Construida con React y TypeScript.',
    section: 'Aplicaciones',
    nav: true,
    order: 1,
    icon: 'globe',
    tags: ['react', 'typescript', 'web'],
    visibility: 'public',
    style: 'featured',
    featured: true,
    hero: { tagline: 'La app que simplifica tu vida' },
    readme: true,
    releases: false,
    links: [
      { label: 'Demo en vivo', url: 'https://example.com', icon: 'globe' },
      { label: 'Código fuente', url: 'https://github.com/demo-user/mi-app', icon: 'code' },
    ],
    badges: [{ label: 'v2.0', color: 'blue' }, { label: 'Producción', color: 'green' }],
    repo: makeRepo('mi-app-increible', 'Una app increíble', ['portal-item', 'react'], 'TypeScript', true, 24),
    readmeContent: `# Mi App Increíble\n\nEsta es la documentación de la app. Aquí puedes explicar todo lo que hace tu proyecto.\n\n## Características\n\n- ✅ Autenticación completa\n- ✅ Panel de usuario\n- ✅ Modo oscuro\n- ✅ Responsive\n\n## Instalación\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\``,
    updatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'herramienta-cli',
    kind: 'download',
    title: 'Herramienta CLI',
    description: 'Utilidad de línea de comandos para automatizar tareas repetitivas en tu flujo de trabajo.',
    section: 'Descargas',
    nav: false,
    order: 2,
    icon: 'terminal',
    tags: ['cli', 'python', 'automatizacion'],
    visibility: 'public',
    style: 'default',
    featured: true,
    readme: false,
    releases: true,
    links: [],
    download: { source: 'latest', label: 'Descargar v1.5.0' },
    badges: [{ label: 'v1.5.0', color: 'purple' }, { label: 'Windows/Mac/Linux', color: 'gray' }],
    latestRelease: {
      id: 1,
      tag_name: 'v1.5.0',
      name: 'Versión 1.5.0',
      published_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
      html_url: 'https://github.com/demo-user/herramienta-cli/releases/tag/v1.5.0',
      assets: [
        { id: 1, name: 'herramienta-linux-amd64', browser_download_url: '#', size: 8_500_000, download_count: 312, content_type: 'application/octet-stream' },
        { id: 2, name: 'herramienta-windows.exe', browser_download_url: '#', size: 9_200_000, download_count: 580, content_type: 'application/octet-stream' },
      ],
      body: 'Correcciones de bugs y mejoras de rendimiento.',
    },
    repo: makeRepo('herramienta-cli', 'CLI para automatizar tareas', ['portal-item', 'cli'], 'Python', false, 87),
    updatedAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'guia-recursos',
    kind: 'card',
    title: 'Guía de Recursos',
    description: 'Colección curada de recursos, tutoriales y referencias sobre desarrollo web moderno.',
    section: 'Proyectos',
    nav: false,
    order: 3,
    icon: 'book',
    tags: ['docs', 'recursos', 'aprendizaje'],
    visibility: 'public',
    style: 'default',
    featured: false,
    readme: false,
    releases: false,
    links: [{ label: 'Ver guía completa', url: '#', icon: 'link' }],
    badges: [],
    repo: makeRepo('guia-recursos', 'Guía de recursos web', ['portal-item'], 'Markdown', false, 15),
    updatedAt: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'mi-blog',
    kind: 'link',
    title: 'Mi Blog Técnico',
    description: 'Artículos sobre programación, arquitectura de software y experiencias en proyectos reales.',
    section: 'Sobre mí',
    nav: true,
    order: 10,
    icon: 'globe',
    tags: ['blog', 'escritura'],
    visibility: 'public',
    style: 'minimal',
    featured: false,
    readme: false,
    releases: false,
    links: [{ label: 'Ir al blog', url: 'https://example.com/blog', icon: 'globe' }],
    action: { type: 'open-url', target: 'https://example.com/blog', label: 'Visitar blog' },
    badges: [],
    repo: makeRepo('mi-blog', 'Blog personal', ['portal-item'], 'Markdown'),
    updatedAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'scripts-utiles',
    kind: 'card',
    title: 'Scripts Útiles',
    description: 'Colección de scripts de shell y Python para automatizar tareas del sistema.',
    section: 'Proyectos',
    nav: false,
    order: 4,
    icon: 'zap',
    tags: ['scripts', 'shell', 'python'],
    visibility: 'public',
    style: 'compact',
    featured: false,
    readme: false,
    releases: false,
    links: [],
    badges: [{ label: 'Útiles', color: 'yellow' }],
    repo: makeRepo('scripts-utiles', 'Scripts de automatización', ['portal-item'], 'Shell', false, 33),
    updatedAt: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'api-personal',
    kind: 'card',
    title: 'API Personal',
    description: 'Backend REST construido con FastAPI. Gestiona datos personales con autenticación JWT.',
    section: 'Proyectos',
    nav: false,
    order: 5,
    icon: 'layers',
    tags: ['python', 'api', 'fastapi', 'backend'],
    visibility: 'public',
    style: 'default',
    featured: false,
    readme: false,
    releases: false,
    links: [],
    badges: [{ label: 'FastAPI', color: 'green' }],
    repo: makeRepo('api-personal', 'API REST personal', ['portal-item'], 'Python', false, 7),
    updatedAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
  },
];
